[2025-08-29T18:50:30.351+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:30:00+00:00 [queued]>
[2025-08-29T18:50:30.506+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:30:00+00:00 [queued]>
[2025-08-29T18:50:30.509+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:30.516+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T18:50:30.519+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:34.489+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-07-26 02:30:00+00:00
[2025-08-29T18:50:34.987+0000] {standard_task_runner.py:52} INFO - Started process 445 to run task
[2025-08-29T18:50:35.130+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'extract', 'scheduled__2025-07-26T02:30:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmprsvfry69', '--error-file', '/tmp/tmpxnfq1csq']
[2025-08-29T18:50:35.193+0000] {standard_task_runner.py:80} INFO - Job 242: Subtask extract
[2025-08-29T18:50:53.954+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:30:00+00:00 [running]> on host b40c5a90b1e4
[2025-08-29T18:51:04.368+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=etl_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-07-26T02:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-26T02:30:00+00:00
[2025-08-29T18:51:13.322+0000] {logging_mixin.py:115} INFO - Success INSERT
[2025-08-29T18:51:12.628+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T18:51:13.603+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-08-29T18:51:14.153+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 445. PIDs of all processes in the group: [445]
[2025-08-29T18:51:14.392+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 445
[2025-08-29T18:51:14.401+0000] {taskinstance.py:1553} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-29T18:51:14.794+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1465, in _run_raw_task
    self.refresh_from_db(lock_for_update=True, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 881, in refresh_from_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 382, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 883, in refresh_from_db
    ti: Optional[TaskInstance] = qry.with_for_update().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 526, in _compile_w_cache
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 555, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 776, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3224, in visit_select
    select_stmt, self, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 674, in create_for_statement
    self._setup_for_generate()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 779, in _setup_for_generate
    entity.setup_compile_state(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/context.py", line 2555, in setup_compile_state
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 621, in _setup_entity_query
    **kw
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 647, in setup
    context, query_entity, path, loader, adapter, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 1997, in setup_query
    chained_from_outerjoin,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 2172, in _generate_row_adapter
    anonymize_labels=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/util.py", line 850, in _memo
    def _memo(self, key, callable_, *args, **kw):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1555, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-29T18:51:16.050+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=extract, execution_date=20250726T023000, start_date=20250829T185030, end_date=20250829T185116
[2025-08-29T18:51:16.438+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 242 for task extract (Task received SIGTERM signal; 445)
[2025-08-29T18:51:16.641+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=445, status='terminated', exitcode=1, started='18:50:34') (445) terminated with exit code 1
[2025-08-29T18:51:16.720+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T18:51:17.562+0000] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:976 SAWarning: Usage of the 'Session.merge()' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
[2025-08-29T18:51:17.647+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
