[2025-08-30T18:29:34.729+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_P2M3_muhammad_al_ghifari.extract manual__2025-08-30T18:29:32.393342+00:00 [queued]>
[2025-08-30T18:29:34.735+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_P2M3_muhammad_al_ghifari.extract manual__2025-08-30T18:29:32.393342+00:00 [queued]>
[2025-08-30T18:29:34.735+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-30T18:29:34.735+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-30T18:29:34.735+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-30T18:29:34.742+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-08-30 18:29:32.393342+00:00
[2025-08-30T18:29:34.746+0000] {standard_task_runner.py:52} INFO - Started process 207 to run task
[2025-08-30T18:29:34.751+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_P2M3_muhammad_al_ghifari', 'extract', 'manual__2025-08-30T18:29:32.393342+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmps5gywjnn', '--error-file', '/tmp/tmpia7nav_e']
[2025-08-30T18:29:34.752+0000] {standard_task_runner.py:80} INFO - Job 325: Subtask extract
[2025-08-30T18:29:34.805+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_P2M3_muhammad_al_ghifari.extract manual__2025-08-30T18:29:32.393342+00:00 [running]> on host ac2c0c50dfcd
[2025-08-30T18:29:34.872+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=ETL_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-08-30T18:29:32.393342+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-30T18:29:32.393342+00:00
[2025-08-30T18:29:34.899+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_muhammad_al_ghifari_DAG.py", line 80, in extract
    df.to_csv('/opt/airflow/data/P2M3_muhammad_ghifari_data_raw.csv', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/P2M3_muhammad_ghifari_data_raw.csv'
[2025-08-30T18:29:34.918+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=ETL_P2M3_muhammad_al_ghifari, task_id=extract, execution_date=20250830T182932, start_date=20250830T182934, end_date=20250830T182934
[2025-08-30T18:29:34.928+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 325 for task extract ([Errno 2] No such file or directory: '/opt/airflow/data/P2M3_muhammad_ghifari_data_raw.csv'; 207)
[2025-08-30T18:29:34.935+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-08-30T18:29:34.966+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
