[2025-08-29T18:39:48.782+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2024-12-28T02:30:00+00:00 [queued]>
[2025-08-29T18:39:48.897+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2024-12-28T02:30:00+00:00 [queued]>
[2025-08-29T18:39:48.900+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:39:48.909+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T18:39:48.924+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:39:49.097+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2024-12-28 02:30:00+00:00
[2025-08-29T18:39:49.111+0000] {standard_task_runner.py:52} INFO - Started process 445 to run task
[2025-08-29T18:39:49.122+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2024-12-28T02:30:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmp5o0acczf', '--error-file', '/tmp/tmpc8z9noda']
[2025-08-29T18:39:49.129+0000] {standard_task_runner.py:80} INFO - Job 62: Subtask preprocess_data
[2025-08-29T18:39:49.854+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2024-12-28T02:30:00+00:00 [running]> on host 30531155033d
[2025-08-29T18:39:50.861+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=etl_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2024-12-28T02:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-28T02:30:00+00:00
[2025-08-29T18:39:50.910+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_muhammad_al_ghifari_DAG.py", line 105, in preprocess_data
    df = pd.read_csv('/opt/airflow/dags/P2M3_muhammad_al_ghifari_data_raw.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/P2M3_muhammad_al_ghifari_data_raw.csv'
[2025-08-29T18:39:51.101+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20241228T023000, start_date=20250829T183948, end_date=20250829T183951
[2025-08-29T18:39:51.216+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 62 for task preprocess_data ([Errno 2] No such file or directory: '/opt/airflow/dags/P2M3_muhammad_al_ghifari_data_raw.csv'; 445)
[2025-08-29T18:39:51.306+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-08-29T18:39:51.803+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
