[2025-08-29T19:03:41.967+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:30:00+00:00 [queued]>
[2025-08-29T19:03:42.075+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:30:00+00:00 [queued]>
[2025-08-29T19:03:42.107+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:42.109+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T19:03:42.115+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:42.944+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-08-09 02:30:00+00:00
[2025-08-29T19:03:43.040+0000] {standard_task_runner.py:52} INFO - Started process 284 to run task
[2025-08-29T19:03:43.215+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T19:03:43.242+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T19:03:43.233+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T19:03:43.267+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T19:03:44.419+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250809T023000, start_date=20250829T190341, end_date=20250829T190344
[2025-08-29T19:03:45.124+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250809T023000, start_date=20250829T190341, end_date=20250829T190345
[2025-08-29T19:03:45.567+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-29T19:03:45.694+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-29T19:03:45.694+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-08-09T02:30:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpugbm_cye', '--error-file', '/tmp/tmpqw6anx0p']
[2025-08-29T19:03:45.702+0000] {standard_task_runner.py:80} INFO - Job 276: Subtask preprocess_data
[2025-08-29T19:03:45.773+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 284. PIDs of all processes in the group: [284]
[2025-08-29T19:03:45.773+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 284
[2025-08-29T19:03:45.839+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=284, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='19:03:42') (284) terminated with exit code Negsignal.SIGTERM
