[2025-08-29T18:50:29.676+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:10:00+00:00 [queued]>
[2025-08-29T18:50:29.927+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:10:00+00:00 [queued]>
[2025-08-29T18:50:29.929+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:29.932+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T18:50:29.942+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:30.299+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-07-26 02:10:00+00:00
[2025-08-29T18:50:30.473+0000] {standard_task_runner.py:52} INFO - Started process 436 to run task
[2025-08-29T18:50:30.631+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'extract', 'scheduled__2025-07-26T02:10:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpa4gbkytu', '--error-file', '/tmp/tmpuj680ta7']
[2025-08-29T18:50:30.690+0000] {standard_task_runner.py:80} INFO - Job 241: Subtask extract
[2025-08-29T18:50:38.559+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:10:00+00:00 [running]> on host b40c5a90b1e4
[2025-08-29T18:51:05.078+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=etl_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-07-26T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-26T02:10:00+00:00
[2025-08-29T18:51:12.852+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T18:51:13.503+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 436. PIDs of all processes in the group: [436]
[2025-08-29T18:51:13.516+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 436
[2025-08-29T18:51:13.825+0000] {taskinstance.py:1553} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-29T18:51:14.947+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_muhammad_al_ghifari_DAG.py", line 80, in extract
    df = pd.read_sql('SELECT * FROM table_m3', conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 634, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1600, in read_query
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 177, in _wrap_result
    frame = _parse_date_columns(frame, parse_dates)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 152, in _parse_date_columns
    for col_name, df_col in data_frame.items():
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 1209, in items
    yield k, self._get_item_cache(k)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3886, in _get_item_cache
    res = self._box_col_values(values, loc).__finalize__(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3868, in _box_col_values
    return klass(values, index=self.index, name=name, fastpath=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 447, in __init__
    generic.NDFrame.__init__(self, data)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1555, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-29T18:51:15.209+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=extract, execution_date=20250726T021000, start_date=20250829T185029, end_date=20250829T185115
[2025-08-29T18:51:15.813+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 241 for task extract (Task received SIGTERM signal; 436)
[2025-08-29T18:51:16.154+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=436, status='terminated', exitcode=1, started='18:50:30') (436) terminated with exit code 1
[2025-08-29T18:51:16.263+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T18:51:17.192+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
