[2025-08-29T18:50:30.442+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:20:00+00:00 [queued]>
[2025-08-29T18:50:31.275+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:20:00+00:00 [queued]>
[2025-08-29T18:50:31.297+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:31.302+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T18:50:31.328+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:32.132+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-07-26 02:20:00+00:00
[2025-08-29T18:50:32.343+0000] {standard_task_runner.py:52} INFO - Started process 441 to run task
[2025-08-29T18:50:32.531+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'extract', 'scheduled__2025-07-26T02:20:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpv96zhy5f', '--error-file', '/tmp/tmpy9n8fz_j']
[2025-08-29T18:50:33.133+0000] {standard_task_runner.py:80} INFO - Job 239: Subtask extract
[2025-08-29T18:50:40.293+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.extract scheduled__2025-07-26T02:20:00+00:00 [running]> on host b40c5a90b1e4
[2025-08-29T18:51:04.884+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=etl_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2025-07-26T02:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-26T02:20:00+00:00
[2025-08-29T18:51:12.250+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T18:51:13.769+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 441. PIDs of all processes in the group: [441]
[2025-08-29T18:51:13.987+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 441
[2025-08-29T18:51:14.067+0000] {taskinstance.py:1553} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-29T18:51:15.179+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_muhammad_al_ghifari_DAG.py", line 80, in extract
    df = pd.read_sql('SELECT * FROM table_m3', conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 634, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1600, in read_query
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 177, in _wrap_result
    frame = _parse_date_columns(frame, parse_dates)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 152, in _parse_date_columns
    for col_name, df_col in data_frame.items():
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 1209, in items
    yield k, self._get_item_cache(k)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3885, in _get_item_cache
    values = self._mgr.iget(loc)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 981, in iget
    block = self.blocks[self.blknos[i]]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 168, in blknos
    if self._blknos is None:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1555, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-29T18:51:15.381+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=extract, execution_date=20250726T022000, start_date=20250829T185030, end_date=20250829T185115
[2025-08-29T18:51:15.995+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 239 for task extract (Task received SIGTERM signal; 441)
[2025-08-29T18:51:16.149+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=441, status='terminated', exitcode=1, started='18:50:31') (441) terminated with exit code 1
[2025-08-29T18:51:16.190+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T18:51:17.130+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
